### PR TITLE
Faster Precompilation

### PR DESCRIPTION
**Pull request by avik-pal**
Essentially https://github.com/SciML/BoundaryValueDiffEq.jl/pull/150/files but without the breaking stuff. I thought we would have to cut a breaking release due to the vector of arrays problem.

## TODO

- [x] Single Shooting
- [x] Multiple Shooting
- [x] MIRK Methods
  - [x] Fix general working
  - [x] JET Tests
- [x] All should return a BVPSolution (Fixes https://github.com/SciML/BoundaryValueDiffEq.jl/issues/44)
- [x] BVProblems now have a NLLS trait for type stable internals
- [x] ODE Interface Methods
  - [x] Fix upstream solution interface for u0 --> function https://github.com/SciML/SciMLBase.jl/pull/567
- [x] Add JET Tests so that this kind of terrible startup regression doesn't  happen
- [x] Needs https://github.com/SciML/SciMLBase.jl/pull/567
- [x] Try handling non-vector inputs more generically.
- [x] Re-enable precompilation
- [x] Enable all tests
  - [x] CI for different hardware
- [x] Remove the manifest toml

The benchmark CI will fail since it is broken on master

### CODE REVIEW

**Comment by avik-pal** [comment]
Persistent tasks failure should be resolved once SciMLBase PR is merged.

**Comment by ChrisRackauckas** [comment]
what PR?

**Comment by avik-pal** [comment]
The one you just merged

**Comment by avik-pal** [comment]
windows failure is just odeinterface acting up. We can merge this now :tada:

**Comment by ChrisRackauckas** [comment]
Remove ODEInterface for Windows. Its binaries require a special installation there.

**Review by ChrisRackauckas — APPROVED** [review]

**Pull request merged**
