### PR TITLE
Fix benchmarks CI

### PR DESCRIPTION
**Pull request by ErikQQY**
Nonlinear solvers should be specified when using `Shooting` methods

### CODE REVIEW

**Comment by ErikQQY** [comment]
This PR should be ready to go

**Comment by avik-pal** [comment]
Seems to fail?

**Comment by ErikQQY** [comment]
I think maybe the CI will work only after PR is merged? I tested locally and the benchmarking scripts are working:

image

**Comment by ChrisRackauckas** [comment]
let's try it

**Pull request merged**
