### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by ErikQQY**
JET CI seems failing because the possible runtime dispatch in NonlinearSolve.jl, so this PR only tests if JET fails for BoundaryValueDiffEq.jl.

Screenshot from 2024-07-13 16-24-23

### CODE REVIEW

**Comment by ErikQQY** [comment]
CI tests for `Shooting` methods in `basic_problems_tests` are weird here, I got all the tests passing in my local environment🤔:

Screenshot from 2024-07-17 23-07-11

**Comment by ChrisRackauckas** [comment]
What's that return code?

**Comment by ErikQQY** [comment]
> What's that return code?

CI hit the Stalled return code in one of the Ray tracing tests, but the testing in local environment is fine.

**Comment by ChrisRackauckas** [comment]
format and we can merge.

**Comment by ChrisRackauckas** [comment]
the benchmark code looks like it needs an update too

**Comment by ErikQQY** [comment]
The benchmark suite for MIRK methods failed because of the current indexing in boundary conditions for shooting methods and MIRK methods are different, e.g. MIRK doesn't support `res[1]=sol(t1)` but shooting methods does, which would require constructing solutions during boundary condition loss evalution like what we did in `Shooting`:

https://github.com/SciML/BoundaryValueDiffEq.jl/blob/20f27f44a43106175c439c2c4488395fc9a82d1b/src/solve/multiple_shooting.jl#L326-L336

Temporarily added different types of benchmarking problems, I will open another PR to unify the indexing in boundary conditions for MIRK and shooting methods.

**Pull request merged**
