### PR TITLE
Overcontrained / Underconstrained BVPs

### PR DESCRIPTION
**Pull request by avik-pal**
Merge https://github.com/SciML/BoundaryValueDiffEq.jl/pull/120 first

- [x] Update All Solvers
  - [x] Shooting
    - [x] MP
    - [x] TP
  - [x] Multiple Shooting
    - [x] MP
    - [x] TP
  - [x] MIRK
    - [x] MP
    - [x] TP
- [x] Testing
  - [x] Shooting
    - [x] MP
    - [x] TP
  - [x] Multiple Shooting
    - [x] MP
    - [x] TP
  - [x] MIRK
    - [x] MP
    - [x] TP
- [x] Update compats for SciMLBase and NonlinearSolve
- [x] Remove Manifest.toml

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by avik-pal** [comment]
Marking it as WIP since I don't know how I broke the tests. I will take a look at this later.

**Comment by avik-pal** [comment]
Banded Matrix for Levenberg seems broken if used with the fast LS path. Arrises from copying the matrix in `mat_tmp`, will probably have to work around this with a custom matrix type / copy function.

**Comment by avik-pal** [comment]
@axla-io this is now ready if you wanted to try out your under-determined models.

**Comment by ChrisRackauckas** [comment]
Open an issue on banded QR for underdetermined systems in LinearSolve.jl? I don't know if anyone will ever get to it but it would be good to track.

**Pull request merged**
