### PR TITLE
Use AlmostBandedMatrix for MIRK Jacobians

### PR DESCRIPTION
**Pull request by avik-pal**
- [x] Support for MIRK
- [x] Benchmarks
- [x] Release and Register `FastAlmostBandedMatrices.jl`
- [x] Support in LinearSolve.jl https://github.com/SciML/LinearSolve.jl/pull/423
- [x] Fix tests (if needed)

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
All of the benchmarks are shooting methods?

**Comment by avik-pal** [comment]
I realized that after the benchmarks ran :sweat:

**Comment by avik-pal** [comment]
image

**Comment by avik-pal** [comment]
Needs a patch for underdetermined systems

**Pull request merged**
